"""Add user roles

Revision ID: 638fe43e2f40
Revises: 
Create Date: 2025-06-29 10:20:13.619476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638fe43e2f40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
